import Head from 'next/head'
import Link from 'next/link'
// 从lib/sanity.js和lib/sanity.server.js文件中导入sanityClient, urlFor
import {urlFor} from '../lib/sanity'
import {sanityClient} from '../lib/sanity.server'

// 这行代码是对数据进行查询，*代表查询全部[]里面写条件,_type=='xxx'是对哪个类进行查询
// 所以这行代码的意思是：我要查询所有的recipe：
// const recipesQuery = `*[_type=='recipe]`
// 我要查询所有的recipe，并只查询name：
// const recipesQuery = `*[_type=='recipe]{name}`
// 我要查询所有的recipe，并只保留_id, name, slug, mainImage这几个字段：
const recipesQuery = `*[_type=='recipe']{
  _id,
  name,
  slug,
  mainImage
}`


export default function Home({recipes}) {
  const {_id, name, slug, mainImage} =recipes
  return (
    <div>
      <Head>
        <title>Cong's Kitchen 🍎</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Cong's Kitchen 🍎</h1>
      <ul className='recipes-list'>
          {recipes?.length>0 && recipes.map((recipe, index) => (
              <li key={recipe._id} className='recipe-card'>
                  <Link href={`/recipes/${recipe.slug.current}`}>
                      {/*需要需要使用urlFor(mainImage).url来获取url地址*/}
                      <a><img src={urlFor(recipe.mainImage).url()} alt={recipe.name}/><span>{recipe.name}</span></a>
                  </Link>
              </li>
          ))}

      </ul>

    </div>
  )
}

export const getStaticProps= async(context)=>{
  // 通过sanityClient.fetch(查询语句)方法来查询数据
  const recipes=await sanityClient.fetch(recipesQuery)
  return {
    props: {
      recipes
    }
  }
}
